### ISSUE TITLE
How to login to jenia with jenkins api token?

### ISSUE THREAD

**Issue by dujianxin** [roman0x58/jenia#1]
We use Gitlab Authentication Plugin in Jenkins. How to login to jenia with Jenkins API token? Thank you very mush!

**Comment by roman0x58** [comment]
Hi! For authentication with Jenkins API token you should use it as password.

**Comment by dujianxin** [comment]
I find that by using the IP instead of the domain can login.
![1](https://user-images.githubusercontent.com/15842774/29646327-5fbc0260-88b5-11e7-99ad-a61386dc64ce.png)
![2](https://user-images.githubusercontent.com/15842774/29646329-61b8aac8-88b5-11e7-9bb5-6aa52a13bea2.png)

**Comment by roman0x58** [comment]
@dujianxin yes, I automatically add 8080 port that's the default jenkins port to server address if is no one provided, so you can explicitly add 80 port to your address. I think this behaviour will be changed in the next release
